"""Hook payload schema validation (OBSERVE-03).

Validates inbound socket payloads against the schemas declared in
``daemon.tts_types`` (``TOOL_EVENT_SCHEMA``, ``STOP_EVENT_SCHEMA``).

Design notes
------------
* The schemas in ``daemon.tts_types`` are *example dicts* — they show field names
  and example values. We use them to derive *required keys* and *expected
  Python types* via ``type(example_value)``. ``"<str>"`` placeholders are
  treated as ``str``; ``0`` / ``0.0`` as ``int`` / ``float``; ``{}`` / ``[]``
  as ``dict`` / ``list``.
* Bar-separated literal placeholders like ``"pre|post"`` are treated as
  enum constraints — value MUST be one of the listed alternatives.
* Nested dicts are validated recursively (``tool_response``).
* Numeric fields accept both ``int`` and ``float`` — ``ts`` is documented as
  ``float`` but Python's ``json.loads`` returns ``int`` for whole numbers.
* Returns ``(ok: bool, violations: list[str])``. ``violations`` is always a
  plain ``list[str]`` so it round-trips cleanly through ``json.dumps``.

Used by:
* ``daemon.tts_daemon.handle_client`` — gates every inbound socket request
  before dispatch to ``_handle_tool_event`` / ``_handle_stop_event``.
* Daemon startup — the schemas are also self-validated against a synthetic
  good payload at boot to catch drift in ``daemon.tts_types``.
"""
from __future__ import annotations

from typing import Any

from daemon.tts_types import (
    TOOL_EVENT_SCHEMA,
    STOP_EVENT_SCHEMA,
    EVENT_RESPONSE_SCHEMA,
)


# Schema registry — maps the `command` string (or symbolic name) to the
# example-dict schema in daemon.tts_types.
_SCHEMAS: dict[str, dict] = {
    "tool_event": TOOL_EVENT_SCHEMA,
    "stop_event": STOP_EVENT_SCHEMA,
    "event_response": EVENT_RESPONSE_SCHEMA,
}

# Per-schema set of TRULY-required top-level keys.  The schemas in
# daemon.tts_types document the *full* shape of the payload (including Claude
# Code passthrough fields like transcript_path / cwd that may legitimately
# be absent in synthetic events — e.g. from `nc -U` testing). Only the
# keys below are checked for presence; all other keys, when present, are
# still type-checked.
#
# Sourced from the comments in daemon/tts_types.py — every field annotated
# "required" or generated by the hook script.
_REQUIRED_KEYS: dict[str, set[str]] = {
    "tool_event": {
        "command", "phase", "event_id", "ts",
        "session_id", "tool_name", "tool_input",
    },
    "stop_event": {
        "command", "session_id", "content", "event_id", "ts",
    },
    "event_response": {
        "status", "event_id",
    },
}

# Per-schema set of nested-field paths that are required when present.
# Format: "<top_key>.<sub_key>" — same as the path emitted by violations.
#
# IMPORTANT: stdout/stderr/interrupted are Bash-shaped only. Other tools
# (Read, Edit, Glob, Grep, Task, WebFetch, ...) ship different tool_response
# shapes — Read returns file content as a string, Edit returns a diff dict,
# etc. Enforcing the Bash shape on every tool is wrong; the validator's
# job is to catch payload-shape *drift*, not to mandate one tool's shape.
# Bash-specific enforcement happens conditionally inside validate_event().
_REQUIRED_NESTED: dict[str, set[str]] = {
    "tool_event": set(),
    "stop_event": set(),
    "event_response": set(),
}

# Tools whose tool_response MUST contain stdout/stderr/interrupted — i.e.
# the Bash-shaped subprocess tools the ContentRouter parses for STATUS/ERROR.
_BASH_SHAPED_TOOLS: frozenset[str] = frozenset({"Bash"})


def _expected_type(example_value: Any) -> tuple:
    """Map an example value to the tuple of acceptable Python types.

    * String placeholders (``"<str>"``, ``"<uuid4>"``, etc.) → ``(str,)``.
    * Bar-separated literal strings (``"pre|post"``) → ``(str,)``; the
      enum check is handled separately.
    * Numeric examples (``0``, ``0.0``) → ``(int, float)`` — JSON parsing
      may return either depending on whether the value looks like a
      whole number.
    * Bool example → ``(bool,)``.
    * dict / list examples → ``(dict,)`` / ``(list,)``.
    """
    if isinstance(example_value, bool):
        return (bool,)
    if isinstance(example_value, (int, float)):
        return (int, float)
    if isinstance(example_value, str):
        return (str,)
    if isinstance(example_value, dict):
        return (dict,)
    if isinstance(example_value, list):
        return (list,)
    return (type(example_value),)


def _enum_alternatives(example_value: Any) -> list[str] | None:
    """If the example value is a bar-separated literal-set placeholder
    (e.g. ``"pre|post"``), return the alternatives. Otherwise return None.

    The schemas use this convention for enum-like fields. Strings wrapped
    in angle brackets (``"<str>"``) are NOT enums — those are type hints.
    """
    if not isinstance(example_value, str):
        return None
    if example_value.startswith("<") and example_value.endswith(">"):
        return None
    if "|" not in example_value:
        return None
    parts = [p.strip() for p in example_value.split("|") if p.strip()]
    return parts if len(parts) > 1 else None


def _validate_against(
    example: dict,
    payload: Any,
    *,
    path: str = "",
    required_keys: set[str] | None = None,
    required_nested: set[str] | None = None,
    nullable_keys: set[str] | None = None,
    lenient_keys: set[str] | None = None,
) -> list[str]:
    """Recursively validate ``payload`` against the example dict schema.

    Args:
        example: The schema example dict from daemon.tts_types.
        payload: The decoded JSON dict to validate.
        path: Current dotted-path (for nested recursion).
        required_keys: Keys whose absence is a violation. If None, ALL
            keys in the example are required (used for nested dicts where
            we recurse with a synthesized requirement set).
        required_nested: Set of dotted paths (e.g. "tool_response.stdout")
            that must exist when their parent is present.

    Returns:
        List of human-readable violation strings (empty == valid).
    """
    if not isinstance(payload, dict):
        return [f"{path or '<root>'}: expected dict, got {type(payload).__name__}"]

    violations: list[str] = []

    for key, example_value in example.items():
        full_key = f"{path}.{key}" if path else key
        is_required = (required_keys is None) or (key in required_keys)

        if key not in payload:
            if is_required:
                violations.append(f"missing required field: {full_key}")
            # Optional + absent — fine, skip type check.
            continue

        actual_value = payload[key]

        # Lenient fields: accept ANY type and skip recursion. Used for a
        # non-Bash tool's tool_response, which is legitimately dict | list | str
        # (Bash=dict, many MCP tools=list, Read/StructuredOutput=str). Dropping
        # the whole event over its shape silenced real tool output (S4).
        if lenient_keys and key in lenient_keys:
            continue
        # Nullable-when-present: optional passthrough fields (transcript_path,
        # cwd, permission_mode, duration_ms, ...) may arrive null from Claude
        # Code. Tolerate null rather than rejecting the event — this was the
        # single largest schema-drop cause (transcript_path:null). Required
        # fields are never in nullable_keys, so they stay strict.
        if actual_value is None and nullable_keys and key in nullable_keys:
            continue

        expected_types = _expected_type(example_value)

        # bool is a subclass of int in Python; for fields whose example is
        # `int` we accept bool too — but for fields whose example is a
        # *bool* we MUST reject ints. Handle that asymmetry.
        if expected_types == (bool,) and not isinstance(actual_value, bool):
            violations.append(
                f"{full_key}: expected bool, got "
                f"{type(actual_value).__name__}"
            )
            continue

        if expected_types == (int, float):
            # bool is an int subclass — reject explicitly.
            if isinstance(actual_value, bool) or not isinstance(actual_value, (int, float)):
                violations.append(
                    f"{full_key}: expected number, got "
                    f"{type(actual_value).__name__}"
                )
                continue

        elif not isinstance(actual_value, expected_types):
            type_names = " or ".join(t.__name__ for t in expected_types)
            violations.append(
                f"{full_key}: expected {type_names}, got "
                f"{type(actual_value).__name__}"
            )
            continue

        # Enum check (bar-separated literal alternatives).
        alternatives = _enum_alternatives(example_value)
        if alternatives is not None and isinstance(actual_value, str):
            if actual_value not in alternatives:
                violations.append(
                    f"{full_key}: value {actual_value!r} not in "
                    f"allowed set {alternatives!r}"
                )

        # Recurse into nested dicts.
        if isinstance(example_value, dict) and example_value:
            # For nested dicts, derive required-keys from required_nested.
            # E.g. "tool_response.stdout" → required key "stdout" inside
            # the recursive call at path="tool_response".
            nested_required: set[str] | None = None
            if required_nested is not None:
                nested_required = {
                    p.split(".", 1)[1]
                    for p in required_nested
                    if p.startswith(f"{full_key}.") and "." in p[len(full_key) + 1:] + "."
                }
                # Above: "tool_response.stdout" yields {"stdout"} when full_key=="tool_response".
                # If nested_required ends up empty AND no top-level required keys
                # specified, fall through to "all keys required" mode for safety.
                if not nested_required:
                    nested_required = set()
            violations.extend(
                _validate_against(
                    example_value, actual_value,
                    path=full_key,
                    required_keys=nested_required,
                    required_nested=required_nested,
                )
            )

    return violations


def validate_event(payload: Any, schema_name: str) -> tuple[bool, list[str]]:
    """Validate ``payload`` against the named schema.

    Args:
        payload: The decoded JSON dict from the socket. Anything other
            than a dict is rejected.
        schema_name: One of ``"tool_event"``, ``"stop_event"``,
            ``"event_response"``.

    Returns:
        ``(ok, violations)`` — ``ok=True`` iff ``violations`` is empty.
        ``violations`` is always a ``list[str]`` for safe JSON logging.
    """
    schema = _SCHEMAS.get(schema_name)
    if schema is None:
        return False, [f"unknown schema name: {schema_name!r}"]

    required_keys = _REQUIRED_KEYS.get(schema_name, set())
    required_nested = set(_REQUIRED_NESTED.get(schema_name, set()))

    # Any optional (non-required) top-level field may legitimately arrive as
    # null from Claude Code (transcript_path, cwd, permission_mode, duration_ms,
    # ...). Tolerate null-when-present rather than DROPPING the whole event —
    # this was the dominant schema-drop cause, silencing Read/Grep/Shell output.
    # Derived from the schema, so new optional fields are auto-tolerated.
    nullable_keys = set(schema.keys()) - set(required_keys)

    # Non-Bash tools have legitimately varied tool_response shapes (dict for
    # Bash, list for many MCP tools, str for Read/StructuredOutput). Accept any
    # shape for a non-Bash tool_response; Bash stays strict (enforced below +
    # via required_nested) because the router parses its stdout for STATUS/ERROR.
    lenient_keys: set[str] = set()
    if (
        schema_name == "tool_event"
        and isinstance(payload, dict)
        and payload.get("tool_name") not in _BASH_SHAPED_TOOLS
    ):
        lenient_keys.add("tool_response")

    # Bash-shape enforcement — only Bash subprocess events MUST carry
    # stdout/stderr/interrupted.
    if (
        schema_name == "tool_event"
        and isinstance(payload, dict)
        and payload.get("tool_name") in _BASH_SHAPED_TOOLS
        and "tool_response" in payload
    ):
        required_nested.update({
            "tool_response.stdout",
            "tool_response.stderr",
            "tool_response.interrupted",
        })

    violations = _validate_against(
        schema, payload,
        required_keys=required_keys,
        required_nested=required_nested,
        nullable_keys=nullable_keys,
        lenient_keys=lenient_keys,
    )
    return (not violations), violations


def validate_schemas_at_startup() -> None:
    """Self-check the schemas at daemon startup.

    Runs each known schema through ``validate_event`` with a synthetic
    payload that exactly mirrors the example dict (with placeholder strings
    coerced to plausible values). Raises ``RuntimeError`` if any schema is
    internally inconsistent — that means daemon.tts_types has been edited in a
    way that breaks the validator. Fail loud at boot rather than silently
    in production.
    """
    def _materialize(example_value: Any) -> Any:
        """Build a value that satisfies ``example_value`` for self-check."""
        if isinstance(example_value, bool):
            return False
        if isinstance(example_value, (int, float)):
            return 0
        if isinstance(example_value, dict):
            return {k: _materialize(v) for k, v in example_value.items()}
        if isinstance(example_value, list):
            return []
        if isinstance(example_value, str):
            alts = _enum_alternatives(example_value)
            if alts is not None:
                return alts[0]
            return "synthetic"
        return None

    for name, schema in _SCHEMAS.items():
        synthetic = {k: _materialize(v) for k, v in schema.items()}
        ok, violations = validate_event(synthetic, name)
        if not ok:
            raise RuntimeError(
                f"schema_validator self-check failed for {name!r}: "
                f"{violations!r}"
            )
